package com.example.bookstoreapp.domain.enums;

public enum CategoryType {
    ART_AND_DESIGN,
    BIOGRAPHY,
    BUSINESS_ECONOMICS_AND_LAW,
    CHILDREN,
    COMPUTING,
    CRIME_AND_THRILLERS,
    EDUCATIONAL,
    FICTION,
    GRAPHIC_NOVELS,
    HEALTH_FOOD_AND_DRINK,
    HISTORY,
    HOME_AND_GARDEN,
    LANGUAGES_AND_REFERENCE,
    LITERATURE_AND_POETRY,
    MEDICAL,
    MUSIC,
    PHILOSOPHY_AND_RELIGION,
    POLITICS,
    SCIENCE_AND_NATURE,
    SCI_FI_FANTASY_AND_HORROR,
    SPORTS_AND_HOBBIES,
    TRAVEL
}
